std = "lua51"
max_line_length = false
exclude_files = {
        ".luacheckrc"
}
globals = {
        "IsAddOnLoaded",
        "Auctionator_Search",
        "TradeSkillUIImprovedDB",
        "UIPanelWindows",
        "TradeSkillFrame",
        "UIParent",
        "CreateFrame",
        "GetAddOnMetadata",
        "floor",
        "HybridScrollFrame_CreateButtons",
        "C_TradeSkillUI",
        "hooksecurefunc",
        "HideUIPanel",
        "GameMenuFrame",
        "TradeSkillUIImproved_CheckButtonHasMaterials",
        "TradeSkillUIImproved_CheckButtonHasSkillUp",
        "TradeSkillUIImproved_CheckButtonHasSkillUpText",
        "TradeSkillUIImproved_CheckButtonHasMaterialsText",
        "SlashCmdList",
        "SLASH_TSUII1",
        "SLASH_TSUII2",
        "CRAFT_IS_MAKEABLE",
        "TRADESKILL_FILTER_HAS_SKILL_UP",
        "GetLocale",
        "InCombatLockdown",
        "GetProfessions",
        "GetProfessionInfo",
        "GetSpellBookItemInfo",
        "GetSpellInfo",
        "BOOKTYPE_PROFESSION",
        "IsCurrentSpell",
        "IsSpellKnown",
        "tonumber",
        "GameFontHighlightSmall",
        "TradeSkillUIImproved_OptionsCheckBoxAuctionatorText",
        "TradeSkillUIImproved_OptionsSliderSizeText",
        "TradeSkillUIImproved_OptionsSliderSizeLow",
        "TradeSkillUIImproved_OptionsSliderSizeHigh",
        "InterfaceOptions_AddCategory",
        "InterfaceOptionsFrame_OpenToCategory",
}
