local moveBar = CreateFrame('Button', nil, TradeSkillFrame)
moveBar:SetPoint('TOPRIGHT', TradeSkillFrame)
moveBar:SetSize(610, 24)
moveBar:SetScript('OnMouseDown', function()
    TradeSkillFrame:SetMovable(true)
    TradeSkillFrame:StartMoving()
end)
moveBar:SetScript('OnMouseUp', function()
    TradeSkillFrame:StopMovingOrSizing()
    TradeSkillFrame:SetMovable(false)

    TradeSkillUIImprovedDB.x = TradeSkillFrame:GetLeft()
    TradeSkillUIImprovedDB.y = TradeSkillFrame:GetTop()
end)
